CPV_CODES = {
    '45': 'Trabajos de construcción',
    '79': 'Servicios a empresas: legislación, mercadotecnia, asesoría, selección de personal, imprenta y seguridad',
    '50': 'Servicios de reparación y mantenimiento',
    '71': 'Servicios de arquitectura, construcción, ingeniería e inspección',
    '72': 'Servicios TI: consultoría, desarrollo de software, Internet y apoyo',
    '92': 'Servicios de esparcimiento, culturales y deportivos',
    '85': 'Servicios de salud y asistencia social',
    '90': 'Servicios de alcantarillado, basura, limpieza y medio ambiente',
    '33': 'Equipamiento y artículos médicos, farmacéuticos y de higiene personal',
    '34': 'Equipos de transporte y productos auxiliares',
    '44': 'Estructuras y materiales de construcción; productos auxiliares para la construcción (excepto aparatos eléctricos)',
    '55': 'Servicios comerciales al por menor de hostelería y restauración',
    '48': 'Paquetes de software y sistemas de información',
    '30': 'Máquinas, equipo y artículos de oficina y de informática, excepto mobiliario y paquetes de software',
    '39': 'Mobiliario (incluido el de oficina), complementos de mobiliario, aparatos electrodomésticos (excluida la iluminación) y productos de limpieza',
    '80': 'Servicios de enseñanza y formación',
    '60': 'Servicios de transporte (excluido el transporte de residuos)',
    '31': 'Máquinas, aparatos, equipo y productos consumibles eléctricos; iluminación',
    '42': 'Maquinaria industrial',
    '66': 'Servicios financieros y de seguros',
    '09': 'Derivados del petróleo, combustibles, electricidad y otras fuentes de energía',
    '98': 'Otros servicios comunitarios, sociales o personales',
    '32': 'Equipos de radio, televisión, comunicaciones y telecomunicaciones y equipos conexos',
    '38': 'Equipo de laboratorio, óptico y de precisión (excepto gafas)',
    '35': 'Equipo de seguridad, extinción de incendios, policía y defensa',
    '77': 'Servicios agrícolas, forestales, hortícolas, acuícolas y apícolas',
    '18': 'Prendas de vestir, calzado, artículos de viaje y accesorios',
    '03': 'Productos de la agricultura, ganadería, pesca, silvicultura y productos afines',
    '63': 'Servicios de transporte complementarios y auxiliares; servicios de agencias de viajes',
    '15': 'Alimentos, bebidas, tabaco y productos afines',
    '64': 'Servicios de correos y telecomunicaciones',
    '51': 'Servicios de instalación (excepto software)',
    '37': 'Instrumentos musicales, artículos deportivos, juegos, juguetes, artículos de artesanía, materiales artísticos y accesorios',
    '22': 'Impresos y productos relacionados',
    '24': 'Productos químicos',
    '14': 'Productos de la minería, de metales de base y productos afines',
    '70': 'Servicios inmobiliarios',
    '73': 'Servicios de investigación y desarrollo y servicios de consultoría conexos',
    '75': 'Servicios de administración pública, defensa y servicios de seguridad social',
    '43': 'Maquinaria para la minería y la explotación de canteras y equipo de construcción',
    '16': 'Maquinaria agrícola',
    '65': 'Servicios públicos',
    '19': 'Piel y textiles, materiales de plástico y caucho',
    '41': 'Agua recogida y depurada',
    '76': 'Servicios relacionados con la industria del gas y del petróleo'
}

